#version: '3'
#services:
#  dl-spring:
#    container_name: dlSpring
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://dldb:3306/dldb
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=qwerty123
#    depends_on:
#      - dldb
#    networks:
#      - my-network
#
#  dldb:
#    container_name: dldb
#    image: mysql/mysql-server:8.0
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_DATABASE=dldb
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=qwerty123
#      - MYSQL_ROOT_PASSWORD=qwerty123
#    networks:
#      - my-network
#networks:
#  my-network:
#    driver: bridge